#!/bin/bash

DAYS=31
LOG=/apps/adhoc-appsetting.log
[ -f $LOG ] || exit  1
[ -n "$1" ] && DAYS=$1

for day in $(grep "^#.*[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]" $LOG |awk '{ print $3 }' | sort -u | tail -$DAYS)
do
    count=$(grep "#.*$day" $LOG | wc -l)
    [ -z "$max" ] && max=$count
    [ $count -gt $max ] && { max=$count;max_day=$day; }
    [ -z "$min" ] && min=$max
    [ $count -le $min ] && { min=$count;min_day=$day; }
    echo "$day  $count"
done
echo "Max: $max_day $max "
echo "Min: $min_day $min "
