#!/bin/bash
PATH=/apps/mead-tools:/apps:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/opt/homebrew/bin:~/bin
FRONTEND_URL="https://repos.wsgc.com/svn/devops/application/frontend-2.1"

BailOut() {
	exec 2>&1
  [ -n "$1" ] && echo "$(basename $0): $*" >&2
  echo "Usage: $(basename $0) <brand> [env]" >&2
  exit 0
}

BRAND=$(tr '[:upper:]' '[:lower:]' <<< $1)
ENVIRO=$(tr '[:upper:]' '[:lower:]' <<< $2)
[[ -z $BRAND ]] && BailOut

[[ $BRAND = "admin" ]] && { echo "600"; exit 0; }
[[ $BRAND = "corp" ]] && { echo "64"; exit 0; }

## special cases to use for prod tooling which doesn't use an env
[[ $ENVIRO =~ ^ca ]] && { BRAND="${BRAND}${ENVIRO}"; ENVIRO=; }

if [[ -n $ENVIRO ]]
then
  POM_URL=$FRONTEND_URL/qa/config/app/trunk/$BRAND/$ENVIRO/pom.xml
  PPOM_URL="$(dirname $(dirname $POM_URL))/pom.xml"
  #SITEID=$(svn cat $POM_URL 2>/dev/null|egrep -i "<frontend.siteId>" | egrep -iv '!--|environment|\${' | awk -F '[<>]' '{ print $3 }' | tr -d "[:space:]" | tr "A-Z" "a-z" | sort -u | egrep -iv "^$" | tail -1)
  #[[ -z $SITEID ]] && SITEID=$(svn cat $PPOM_URL 2>/dev/null|egrep -i "<frontend.siteId>" | egrep -iv '!--|environment|\${' | awk -F '[<>]' '{ print $3 }' | tr -d "[:space:]" | tr "A-Z" "a-z" | sort -u | egrep -iv "^$" | tail -1)
  SITEID=$(getsiteid $BRAND $ENVIRO)
  [[ -n $SITEID ]] && { echo "$SITEID"; exit 0; }
fi

if [[ -z $ENVIRO ]]
then
  case $BRAND in
	  mg | us*mg* | mgus* ) SITEID="66" ;;
	  ca*mg | mg*ca* ) SITEID="76" ;;

	  pb | uspb* | pbus* ) SITEID="63" ;;
	  ca*pb | pb*ca* ) SITEID="73" ;;

	  pk | us*pk*| pkus* ) SITEID="65" ;;
	  ca*pk | pk*ca* ) SITEID="75" ;;

	  pt | us*pt* | ptus* ) SITEID="67" ;;
	  ca*pt | pt*ca* ) SITEID="77" ;;

	  we | us*we* | weus* ) SITEID="69" ;;
	  ca*we | we*ca* ) SITEID="79" ;;

	  ws | us*ws* | wsus* ) SITEID="61" ;;
	  ca*ws | ws*ca* ) SITEID="71" ;;

	  rj | us*rj* | rjus* ) SITEID="62" ;;
	  ca*rj | rj*ca* ) SITEID="72" ;;

	  nb ) SITEID="68" ;;
	  gr | us*gr* | grus* ) SITEID="68" ;;
	  ca*gr | gr*ca* ) SITEID="78" ;;

	  admin ) SITEID="600" ;;
  esac
fi

[[ -n $SITEID ]] && { echo "$SITEID"; exit 0; }

echo "$(basename $0): No siteId found for $BRAND $ENVIRO" >&2

exit 0
