#!/bin/bash
PATH=/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/apps/mead-tools:~/bin
# todo: check result on port 49446
HEADER="Cache-Control: no-cache, must-revalidate, max-age=0"
#PRAGMA="Pragma: no-cache, akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-extracted-values, akamai-x-get-nonces, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-serial-no, akamai-x-get-true-cache-key, akamai-x-get-request-id, akamai-x-get-client-ip, x-akamai-staging, akamai-x-feo-trace, x-true-cache-key"
PRAGMA="Pragma: akamai-grn"
LOGIN="ptqaenv:ta8PoLe"
TIMEOUT="--connect-timeout 10 --max-time 20"
PAUSE=1

B=$1
E=$2
T=$3

BailOut() {
	echo "Usage: $(basename $0) <brand> <env>"
	exit 1	
}

[[ -z $E ]] && BailOut

AKAMAI=$(get-akamai $B $E | sed -e s%https://%%g)

[ -z "$AKAMAI" ] && BailOut "No Akamai URL"
#[ -z "$AKAMAI" ] && echo "No AKAMAI URL"

FRONTEND=$(geturls $B $E | grep -i "frontend:" | awk '{ print $NF}' | sed -e s!https://!!g )
ORIGIN="origin-$AKAMAI"

FRONTEND_IP=$(host $FRONTEND 2>/dev/null |grep -i address | awk '{ print $NF}')
ORIGIN_IP=$(host $ORIGIN 2>/dev/null |grep -i address | awk '{ print $NF}')
AKAMAI_IP=$(host $AKAMAI 2>/dev/null |grep -i address | awk '{ print $NF}')
EDGE=$(host $AKAMAI 2>/dev/null |grep -i alias | head -1 | awk '{ print $NF}')
HOST=$(curl $TIMEOUT --user "$LOGIN" -sqk https://$AKAMAI/admin/summary.html | grep -i "secondary-Secure---Nonsecure-URL-Pairs" | awk -F '[<>]' '{ print $13 }' | awk -F '[{}]' '{ print $2 }' | awk -F/ '{ print $3 }')
echo "$HOST" | grep -iq "wsgc.com" || HOST="$HOST.wsgc.com"

echo "Akamai:   $AKAMAI"
echo "Frontend: $FRONTEND"
echo "Edge:     $EDGE"
#echo "Mapping:  $HOST"

#for TEST in "Frontend|$FRONTEND|$FRONTEND_IP" "Frontend:49446|$FRONTEND:49446|$FRONTEND_IP" "Origin|$ORIGIN|$ORIGIN_IP" "Akamai|$AKAMAI|$AKAMAI_IP"
#for TEST in "Frontend|$FRONTEND.wsgc.com|$FRONTEND_IP" "Akamai'd|$AKAMAI|$AKAMAI_IP"
#    "OrgnIP|$ORIGIN_IP|$ORIGIN_IP" \
for TEST in \
    "Server|$FRONTEND|$FRONTEND_IP" \
    "Origin|$ORIGIN|$ORIGIN_IP" \
    "Akamai|$AKAMAI|$AKAMAI_IP" 
do
	LABEL=$(echo $TEST | awk -F\| '{ print $1 }')
	URL=$(echo $TEST | awk -F\| '{ print $2 }')
	IP=$(echo $TEST | awk -F\| '{ print $3 }')

	sleep $PAUSE
	H="curl $TIMEOUT -Ik -s --header "$HEADER" --header "$PRAGMA" --user "$LOGIN" https://$URL/ 2>&1 | head -n 1|cut -d$' ' -f2"
	sleep $PAUSE
	C="curl $TIMEOUT -k -s --header "$HEADER" --header "$PRAGMA" --user "$LOGIN" https://$URL/ 2>&1 | egrep -i -A+1 '<body>|<head>' | tail -1"

	#echo "$LABEL	$IP	https://$URL			$(eval $H)				$(eval $C)"
	echo "$LABEL    $IP	https://$URL			$(eval $C)"
done
echo


