#!/bin/bash 
export PATH=$JAVA_HOME/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/apps/mead-tools:/home/jenkins/node_modules/.bin:/opt/homebrew/bin:~/bin

export KUBE_USER="svcak8sci"
[[ -e $HOME/.kube ]] && KUBE_CONFIG_PATH="$HOME/.kube"
[[ -e /var/lib/jenkins/.kube ]] && KUBE_CONFIG_PATH="/var/lib/jenkins/.kube"
export KUBE_CLUSTER="ts-sharedplatform-rck-nonprod"
export KUBE_CONTEXT="${KUBE_CLUSTER}_${KUBE_USER}@wsgc.com"
export KUBE_CONFIG="${KUBE_CONFIG_PATH}/${KUBE_USER}/${KUBE_CLUSTER}"

BailOut() {
  [[ -n $1 ]] && echo "$(basename $0): $*"  >&2
  exit 255
}

[[ $LOGNAME = jenkins ]] || BailOut "Need to run as Jenkins"

[[ -n $KUBE_CONFIG_PATH ]] || BailOut "KUBE_CONFIG_PATH is blank"
[[ -e $KUBE_CONFIG_PATH ]] || BailOut "$KUBE_CONFIG_PATH missing"
[[ -e $KUBE_CONFIG ]] || BailOut "$KUBE_CONFIG missing"
[[ -n $KUBE_CONTEXT ]] || BailOut "KUBE_CONTEXT is blank"
which kubectl >/dev/null 2>&1 || BailOut "Can't find kubectl"
which kubelogin >/dev/null 2>&1 || BailOut "Can't find kubelogin"

NS=$1
BRAND=$2

[[ -z $NS ]] && BailOut "Need namespace"
[[ -z $BRAND ]] && BailOut "Need brand"

echo "Namespace:  $NS"
echo "Brand:      $BRAND"

for POD in $(kubectl --kubeconfig=$KUBE_CONFIG get pods -n $NS | egrep -vi "^NAME" | grep ecom-svc-catalog-$BRAND | awk '{ print $1 }')
do
  echo "Pod:        $POD"
  kubectl --kubeconfig=$KUBE_CONFIG exec -it $POD --namespace $NS -- bash -c "ls -ldGg /opt/catalog/archives/catalogdata/ 2>/dev/null | egrep -iv 'total'" 2>/dev/null
  kubectl --kubeconfig=$KUBE_CONFIG exec -it $POD --namespace $NS -- bash -c "ls -lhGg /opt/catalog/archives/catalogdata/ 2>/dev/null | egrep -iv 'total'" 2>/dev/null
  echo
done

exit 0
