#!/bin/bash
PATH=/apps/mead-tools:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:$HOME/bin:$PATH

[ $(hostname) = "artrck-vccn004" -o $(hostname) = "artrck-vicn003" ] || exit 1

BRANCH=$(git branch | grep '\*' | awk '{ print $NF }')
[[ -n $1 ]] && INSTALL=$1 || INSTALL=master
git checkout $INSTALL || exit 1

sudo rm -f /apps/mead-tools/get-adg-delivery

FILES="get-env-team cleanup-mead-tools take-note get-catalog* setenv-mead ecm2gen test-svn-access jenkins-jnlp jmxclient.jar SSLPoke.class jira-* getbrand get-domain getdomain getsiteid get-siteid get-site-id getversion getschema  propset propget propcopy geturls site2market market2label label2market slack-comment get-market getmarket yq  getdbenv getakamai getbrandlist copy-prod-generations getoverride get-override-url getoauthhost update-etcd-bootstrap-records set-oauth get-brand-list get-buildsystem-host get-buildsystem-url get-deployment-properties get-akamai get-origin get-mfe-generations get-dp-generations get-dp-setting parse-log get-installation get-env-list get-oauth-host get-overridescope get-appsetting-job get-dp-schema chkschema get-etcd-* get-ecm-* get-bgb-* get-adg-* get-manifest getdb get-db get-backend sync-fork get-job-history"

git pull

sudo cp $FILES /apps/mead-tools
cd /apps/mead-tools
sudo chmod 775 $FILES
sudo chown tomcat:webadmin $FILES

[[ -e /usr/local/bin/yq ]] || sudo cp yq /usr/local/bin
rpm -qa | grep -iq jq || sudo yum -y install jq -d0

exit 0

cp $FILES /tmp

cat > /tmp/mead-install.sh << EOF
#!/bin/bash

cd /tmp
cp $FILES /apps/mead-tools
cd /apps;chown tomcat:webadmin $FILES
chmod 775 $FILES

rpm -qa |grep -iq wsgc-devops-toolchain-scm-tools || wsgc-install wsgc-devops-toolchain-scm-tools

EOF

sudo sh /tmp/mead-install.sh

rpm -qa | grep -iq "^dos2unix" || sudo yum -y install dos2unix -d0
rpm -qa | grep -iq "^hub" || sudo yum -y install hub -d0
rpm -qa | grep -iq "^jq" || sudo yum -y install jq -d0

