#!/bin/bash
# backend setting scriptlet for eqa1/dtc_app_owner
#
echo "/// [$(basename $0)-dtc_app_owner] Backend settings for $BRAND $ENVIRO $BACKEND ///"

[[ -z $BRAND || -z $ENVIRO || -z $BACKEND ]] && { echo "*** This script is not meant to be run standalone - use 'set-backend' ***"; exit 255; }

echo "* update manifest $BRAND $ENVIRO"
#set-manifest-property -b $BRAND -e $ENVIRO -s ecom-svc-order-servicing -p catalogservice.serviceUrl -v https://%s-ecommerce-ecom-svc-catalog-qa1.services.west.wsgc.com/api/catalog/v1

#echo "* update $(basename  $VALUES)"
#cd $TMP/syncappconfig/config || BailOut "<$(basename $0)> Unable to cd to syncappconfig/config"
#VALUES=$ENVIRO/values.yaml
#yq eval -i ".\"services\".\"registryAppService\".\"uri\" = \"https://ecommerce-ecom-svc-registry-rgs1.services.west.nonprod.wsgc.com/\"" $VALUES
#yq eval -i ".\"services\".\"registryMfe\".\"uri\" = \"https://ecommerce-ecom-app-registry-rgs1.services.west.nonprod.wsgc.com/\"" $VALUES
#{ set +x; } 2>/dev/null

echo "* update appsettings"
#set -x

wsi_settings.sh "$COMMENTS" --brand $BRAND --env $ENVIRO -v --bulk "ECOMSERV.STORE_ESTIMATE_SERVICE_URI.r=https://retailordersqa4.wsgc.com/UISCOM/api/v1/estimate/"
wsi_settings.sh "$COMMENTS" --brand $BRAND --env $ENVIRO -v --bulk "ECOMSERV.STORE_ESTIMATE_REST_REDIRECT_URI.r=https://retailordersqa4.wsgc.com/UISCOM/Estimates/CSORedirect.aspx?estimateId="

wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk  PRODUCT_CONFIGURATOR.SERVICE_URI.r=https://eqa1-product-configuration-service-supplychain.services.west.nonprod.wsgc.com/v1/products
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMREG.REG_STS_COOKIENAME.s=${BRAND_UC}MX_REGSTS_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMEXP.EXPRESS_CHECKOUT_COOKIE.s=${BRAND_UC}EXPRESS_CHECKOUT_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMPRF.PERSISTENT_METRICS_COOKIE.s=${BRAND_UC}_PCMETRICS_COOKIE_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMPRF.PRF_COOKIENAME.s=${BRAND_UC}MX_SIGNIN_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMPRF.USER_PERSIST_COOKIE_NAME.s=${BRAND_UC}MX_PERSIST_COOKIE_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMPRF.ACCT_COOKIENAME.s=${BRAND_UC}MX_ACCT_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMPRF.TEXT_ME_OFFERS_ENABLED.b=false

wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMSES.DATATABLE.s=${BRAND_UC}PE_SESSION_DATA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMSES.INFOTABLE.s=${BRAND_UC}PE_SESSION_INFO
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMSES.COOKIENAME.s=${BRAND_UC}PE_SID_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMSES.POTENTIALSECURECOOKIENAME.s=${BRAND_UC}PE_PSSID_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMSES.SECURECOOKIENAME.s=${BRAND_UC}PE_SSID_QA

wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMCRT.SAVEDCARTCOOKIE.s=${BRAND_UC}MX_SAVEDCART_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMCRT.SESSIONCARTCOOKIE.s=${BRAND_UC}MX_SESCART_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMCAT.BANNERCOOKIE.s=${BRAND_UC}MX_BANNERS_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk COMCRT.MAXSESSIONTIME.t=1,1,0,0

wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk CHKT.KAFKA_TOPIC_PREFIX.s=QA1.B.
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk AFFIRM.EPS_TOKEN_SCHEME.s=AFP_PMNT_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk VENMO.EPS_TOKEN_SCHEME.s=BTVT_PMNT_QA
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk CART_CHECKOUT.SERVICE_URI.r=https://ecommerce-cart-checkout-qa1.services.west.nonprod.wsgc.com/cartservice/v1/domain/
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk ORDER_HISTORY_SERVICE.URL.s=https://eqa1-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/orderservice/v1/history
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk ORDER_SERVICE.URL.s=https://eqa1-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/orderservice/v1/orders/
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk SELF_SERVICE.APPOINTMENTS_URL.s=https://eqa1-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/appointment/v1/workorders/
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk SELF_SERVICE.RESCHEDULE_ELIGIBILITY_URL.s=https://eqa1-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/appointment/reschedule/v1/workorders/
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk SINGLE_PAGE_CHECKOUT.CARE_CENTER_REDIRECT_BASE_URL.r=https://eqa1-ccui.wsgc.com/oms/#/detail/order/default/
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk TRACKING_SERVICE.URL.s=https://eqa1-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/trackingservice/v1/
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk TRACKING_SERVICE.THIRD_PARTY_SERVICE_URI.r=https://eqa1-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/shipments/tracking/details
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk LOYALTY.KAFKA_TOPIC_PREFIX.s=QA1.L.
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk UPS_TRACKING_SERVICE.SERVICE_URI.r=https://tibinttstmp7p.wsgc.com:19109/v1/GetTrackingDetails
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk PAYMENT.TOKENIZATION_EPS_URLS.a=https://tibinttstmp7p.wsgc.com:19092/paymentservice/v1
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk ORDER_RETURN_DETAILS_SERVICE.SERVICE_URI.r=https://tibinttstmp7p.wsgc.com:19105/v1/GetOrderReturnEligibility
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk ORDERSCREENING.SERVICE_URL.s=https://tibinttstmp7p.wsgc.com:19096/ecommerce/orderfraudscreening
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk INVENTORY_OMS_RESERVATION_REST.SERVICE_URI.r=https://tibinttstmp7p.wsgc.com:19110
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk INVENTORY_OMS_REST.SERVICE_URI.r=https://tibinttstmp7p.wsgc.com:19104
wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk PAYMENT.TOKENIZATION_EPS_SCC_SCHEME.s=WSI_SCC_QA
{ set +x; } 2>/dev/null

echo "* update $(basename $POM)"
#set -x
propset -f $POM -p frontend.jmsOrderCreate.password -v n3tw0rk
propset -f $POM -p frontend.jmsOrderCreate.providerUrl -v tcp://tibinttstmp1p.wsgc.com:20001
propset -f $POM -p frontend.jmsOrderCreate.username -v apptibco
propset -f $POM -p frontend.jmsOrder.password -v n3tw0rk
propset -f $POM -p frontend.jmsOrderPricing.password -v n3tw0rk
propset -f $POM -p frontend.jmsOrderPricing.providerUrl -v tcp://tibinttstmp1p.wsgc.com:20001
propset -f $POM -p frontend.jmsOrderPricing.username -v apptibco
propset -f $POM -p frontend.jmsOrder.providerUrl -v tcp://tibinttstmp3p.wsgc.com:20011
propset -f $POM -p frontend.jmsOrderReservation.password -v n3tw0rk
propset -f $POM -p frontend.jmsOrderReservation.providerUrl -v tcp://tibinttstmp1p.wsgc.com:20001
propset -f $POM -p frontend.jmsOrderReservation.username -v apptibco
propset -f $POM -p frontend.jmsOrder.username -v apptibco
propset -f $POM -p frontend.jms.password -v n3tw0rk
propset -f $POM -p frontend.jms.providerUrl -v tcp://tibintpprdrk1p.wsgc.com:10006
propset -f $POM -p frontend.jms.subscriberClientId -v @NODENAME@
propset -f $POM -p frontend.jms.username -v apptibco
propset -f $POM -p frontend.jmsWismo.password -v n3tw0rk
propset -f $POM -p frontend.jmsWismo.passwordCov2 -v n3tw0rk
propset -f $POM -p frontend.jmsWismo.providerUrl -v tcp://tibinttstmp1p.wsgc.com:20001
propset -f $POM -p frontend.jmsWismo.username -v apptibco
propset -f $POM -p frontend.jmsWismo.usernameCov2 -v apptibco
{ set +x; } 2>/dev/null

if [[ $MARKET = "CAN" ]]
then
  echo "* update $MARKET-specific settings"
#set -x
  #yq eval -i ".\"services\".\"shopMfe\".\"uri\" = \"https://ecommerce-ecom-app-shop-eqa1.services.west.nonprod.wsgc.com/\"" $VALUES
  #yq eval -i ".\"services\".\"inventoryAppService\".\"uri\" = \"https://WS-ecommerce-ecom-svc-catalog-ca2.services.west.nonprod.wsgc.com/api/inventory/v1/\"" $VALUES
  #yq eval -i ".\"services\".\"catalogAppService\".\"uri\" = \"https://WS-ecommerce-ecom-svc-catalog-ca2.services.west.nonprod.wsgc.com/api/catalog/v1/\"" $VALUES

  wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk 'PIP.FULFILLMENT_COUNTRY_CODE.a=CA'
  wsi_settings.sh --brand $BRAND --env $ENVIRO -v --bulk GEO_PROVINCES_API.STATES_PROVINCES_URL.s=https://ecommerce-ecom-svc-customer-eqa1.services.west.nonprod.wsgc.com/api/geo/v1/provinces.json

{ set +x; } 2>/dev/null
fi

