#!/bin/bash
# backend setting scriptlet for eqa2/veqa2
#
echo "/// [$(basename $0)-veqa2] Backend settings for $BRAND $ENVIRO $BACKEND ///"

[[ -z $BRAND || -z $ENVIRO || -z $BACKEND ]] && { echo "*** This script is not meant to be run standalone - use 'set-backend' ***"; exit 255; }

echo "* update manifest $BRAND $ENVIRO"
set -x
#eval $SMP -p shared -v $BACKEND-shared -s pricing 
#eval $SMP -p shared -v $BACKEND-shared -s pricing-singleuse-batch-generator
#eval $SMP -p shared -v $BACKEND-shared -s promo-publisher 
#eval $SMP -p shared -v $BACKEND-shared -s cart-checkout 
#eval $SMP -p shared -v $BACKEND-shared -s inventory-service
#eval $SMP -p shared -v $BACKEND-shared -s ecom-svc-catalog 
#eval $SMP -p shared -v $BACKEND-shared -s catalog-pb 
#eval $SMP -p shared -v $BACKEND-shared -s registryv2
#eval $SMP -p shared -v $BACKEND-shared -s registryv3
#eval $SMP -p shared -v $BACKEND-shared -s membership-service
#eval $SMP -p shared -v $BACKEND-shared -s ecom-svc-registry
#eval $SMP -p shared -v $BACKEND-shared -s ecom-app-registry
#eval $SMP -p shared -v $BACKEND-shared -s ecom-app-phygital
{ set +x; } 2>/dev/null

echo "* update appsettings $BRAND $ENVIRO"

domkey=$(get-domain $BRAND $ENVIRO | awk -F\. '{ print $1 }' | sed -es/-//g)

#set -x

$UPDATE_SETTING GEO_PROVINCES_API.STATES_PROVINCES_URL.s=https://ecommerce-ecom-svc-customer-eqa2.services.west.nonprod.wsgc.com/api/geo/v1/provinces.json

$UPDATE_SETTING "ECOMSERV.STORE_ESTIMATE_SERVICE_URI.r=https://retailordersqa2.wsgc.com/UISCOM/api/v1/estimate/"
$UPDATE_SETTING "ECOMSERV.STORE_ESTIMATE_REST_REDIRECT_URI.r=https://retailordersqa2.wsgc.com/UISCOM/Estimates/CSORedirect.aspx?estimateId="

$UPDATE_SETTING COMAVS.AVS_REST_SERVICE_URL.s=https://ecommerce-avs-service-qa.services.west.nonprod.wsgc.com/address-verification-service/v1/
$UPDATE_SETTING APPLE_PAY.EPS_TOKEN_SCHEME.s=BTVT_PMNT_QA2 
$UPDATE_SETTING APPLE_PAY.MERCHANT_IDENTIFIER.s=merchant.com.williams-sonoma.sandbox

$UPDATE_SETTING PAYPAL.EPS_TOKEN_SCHEME.s=BTPP_PMNT_QA2
$UPDATE_SETTING PAYMENT.TOKENIZATION_EPS_URLS.a=https://tibinttstsac5p.wsgc.com:19092/paymentservice/v1

$UPDATE_SETTING SINGLE_PAGE_CHECKOUT.COUNTDOWN_TIMER_AB_ENABLED.b=true
$UPDATE_SETTING UPS_TRACKING_SERVICE.SERVICE_URI.r=https://TIBINTTSTSAC5P.wsgc.com:19109/v1/GetTrackingDetails
$UPDATE_SETTING CREATE_ONLINE_RETURN_SERVICE.SERVICE_URI.r=https://TIBINTTSTSAC5P.wsgc.com:19106/v1/CreateOnlineReturn
$UPDATE_SETTING GET_RETURN_LABEL_SERVICE.SERVICE_URI.r=https://TIBINTTSTSAC5P.wsgc.com:19107/v1/GetReturnLabel
$UPDATE_SETTING ORDER_SHIPMENT_DETAILS_SERVICE.SERVICE_URI.r=https://TIBINTTSTSAC5P.wsgc.com:19101/v1/GetOrderShipmentDetails

$UPDATE_SETTING DOMAIN_PUBLISHER_CLIENT.DOMAIN_PUBLISHER_OVERRIDE_KEY.s=${domkey}_${REALM}

$UPDATE_SETTING AB_TESTS.GLOBAL_AB_TESTS_ENABLED.b=false
[[ $BRAND = "we" ]] && wsi_settings.sh "$COMMENTS" --brand we     --env $ENVIRO -v --bulk AB_TESTS.GLOBAL_AB_TESTS_ENABLED.b=true

$UPDATE_SETTING ORDER_INVOICE.SERVICE_URI.r=https://eqa2-order-service-supplychain.services.west.nonprod.wsgc.com/orderinvoice/v1/orders/
$UPDATE_SETTING BIZSALES.SERVICE_URI.r=https://ecommerce-salesforceconnector-qa.services.west.nonprod.wsgc.com/designer-service/v2/designer/
$UPDATE_SETTING PRICING.PROMOTION_SERVICE_URI.r=https://ecommerce-pricing-veqa2.services.west.nonprod.wsgc.com
$UPDATE_SETTING PRICING.SERVICE_URI.r=https://ecommerce-pricing-veqa2.services.west.nonprod.wsgc.com
$UPDATE_SETTING PIPSTRATEGY.SPLIT_STRATEGY_ENABLED.b=false
$UPDATE_SETTING PIPSTRATEGY.NEXT_GEN_PIP_MOBILE_ATTRIBUTES_ENABLED.b=false
$UPDATE_SETTING PIPSTRATEGY.PARSING_ENABLED.b=false
$UPDATE_SETTING PIPSTRATEGY.SPLIT_STRATEGY_ENABLED.b=false
$UPDATE_SETTING PIP_ASSORTMENT_CONFIGURATION.BUNDLESET_EXPLODING_ENABLED.b=true
$UPDATE_SETTING PIP_ASSORTMENT_CONFIGURATION.COMPRESSION_DESKTOP_ENABLED.b=false
$UPDATE_SETTING PIP_ASSORTMENT_CONFIGURATION.COMPRESSION_ENABLED.b=false
$UPDATE_SETTING PIP_ASSORTMENT_CONFIGURATION.COMPRESSION_MOBILE_ENABLED.b=false
$UPDATE_SETTING PIP_DISPLAY.BORDERFREE_LOCALIZATION_ENABLED.b=false
$UPDATE_SETTING PIP_DISPLAY.BYPASS_CLIENT_SIDE_EDGE_CACHING.b=false
$UPDATE_SETTING PIP_DISPLAY.CLIENT_SIDE_ACCOUNT_VALIDATION_ENABLED.b=false
$UPDATE_SETTING PIP_DISPLAY.USE_CLIENT_SIDE_LOGIN_CHECK.b=false
$UPDATE_SETTING PIP_DISPLAY.SMART_IMAGES_ENABLED.b=false
$UPDATE_SETTING DREAM_PIP.AB_TEST_ENABLED.b=false
$UPDATE_SETTING DREAM_PIP.PIP_STRATEGY_ENABLED.b=false
$UPDATE_SETTING INVENTORY.INVENTORY_MICROSERVICE_URI.r=https://ecommerce-inventory-service-veqa2.services.west.nonprod.wsgc.com/inventory/v2
$UPDATE_SETTING CART_CHECKOUT.SERVICE_URI.r=https://ecommerce-cart-checkout-veqa2.services.west.nonprod.wsgc.com/cartservice/v1/domain/
$UPDATE_SETTING CART_CHECKOUT.SOCKET_TIMEOUT.i=50000
$UPDATE_SETTING ORDER_HISTORY_SERVICE.URL.s=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/orderservice/v1/history
$UPDATE_SETTING PRODUCT_CONFIGURATOR.SERVICE_URI.r=https://eqa2-product-configuration-service-supplychain.services.west.nonprod.wsgc.com/v1/products
$UPDATE_SETTING ORDER_SERVICE.URL.s=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/orderservice/v1/orders/
$UPDATE_SETTING SELF_SERVICE.APPOINTMENTS_URL.s=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/appointment/v1/workorders/
$UPDATE_SETTING TRACKING_SERVICE.URL.s=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/trackingservice/v1/
$UPDATE_SETTING TRACKING_SERVICE.THIRD_PARTY_SERVICE_URI.r=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/shipments/tracking/details
#$UPDATE_SETTING COMPRF.PERSISTENT_METRICS_COOKIE.s=${BRAND_UC}_PCMETRICS_COOKIE_QA
#$UPDATE_SETTING COMPRF.USER_PERSIST_COOKIE_NAME.s=${BRAND_UC}MX_PERSIST_COOKIE_QA
#$UPDATE_SETTING COMPRF.PRF_COOKIENAME.s=${BRAND_UC}MX_SIGNIN_QA
#$UPDATE_SETTING COMPRF.TEXT_ME_OFFERS_ENABLED.b=false

$UPDATE_SETTING COMCRT.SAVEDCARTCOOKIE.s=${BRAND_UC}MX_SAVEDCART_QA2
$UPDATE_SETTING COMCRT.SESSIONCARTCOOKIE.s=${BRAND_UC}MX_SESCART_QA2
$UPDATE_SETTING COMCAT.BANNERCOOKIE.s=${BRAND_UC}MX_BANNERS_QA2

#$UPDATE_SETTING COMSES.DATATABLE.s=${BRAND_UC}PE_SESSION_DATA
$UPDATE_SETTING COMSES.COOKIENAME.s=${BRAND_UC}PE_SID_QA2
$UPDATE_SETTING COMSES.POTENTIALSECURECOOKIENAME.s=${BRAND_UC}PE_PSSID_QA2
$UPDATE_SETTING COMSES.SECURECOOKIENAME.s=${BRAND_UC}PE_SSID_QA2

#$UPDATE_SETTING COMREG.REG_STS_COOKIENAME.s=${BRAND_UC}MX_REGSTS_QA

$UPDATE_SETTING CHKT.KAFKA_TOPIC_PREFIX.s=QA2.B.
$UPDATE_SETTING AFFIRM.EPS_TOKEN_SCHEME.s=AFP_PMNT_QA2
$UPDATE_SETTING VENMO.EPS_TOKEN_SCHEME.s=BTVT_PMNT_QA2
$UPDATE_SETTING SELF_SERVICE.RESCHEDULE_ELIGIBILITY_URL.s=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/appointment/reschedule/v1/workorders/
$UPDATE_SETTING LOYALTY.KAFKA_TOPIC_PREFIX.s=QA2.L.
$UPDATE_SETTING UPS_TRACKING_SERVICE.SERVICE_URI.r=https://tibinttstmp7p.wsgc.com:19109/v1/GetTrackingDetails
$UPDATE_SETTING ORDER_RETURN_DETAILS_SERVICE.SERVICE_URI.r=https://tibinttstsac5p.wsgc.com:19105/v1/GetOrderReturnEligibility
$UPDATE_SETTING ORDERSCREENING.SERVICE_URL.s=https://tibinttstsac5p.wsgc.com:19096/ecommerce/orderfraudscreening
$UPDATE_SETTING ORDER_INVOICE.SERVICE_URI.r=https://eqa2-wsi-gateway-supplychain.services.west.nonprod.wsgc.com/gateway/process/orderinvoice/v1/orders/
$UPDATE_SETTING INVENTORY_OMS_RESERVATION_REST.SERVICE_URI.r=https://tibinttstsac5p.wsgc.com:19110
$UPDATE_SETTING INVENTORY_OMS_REST.SERVICE_URI.r=https://tibinttstsac5p.wsgc.com:19104
$UPDATE_SETTING PAYMENT.TOKENIZATION_EPS_SCC_SCHEME.s=WSI_SCC_QA2
$UPDATE_SETTING ECOMSERV.STORE_ORDER_CONFIRMATION_URL.s=https://retailordersqa2.wsgc.com/UIScom/Estimates/OrderUpdate.aspx

#$UPDATE_SETTING SINGLE_PAGE_CHECKOUT.CARE_CENTER_REDIRECT_BASE_URL.r=https://eqa2-ccui.wsgc.com/oms/#/detail/order/default/
#$UPDATE_SETTING SINGLE_PAGE_CHECKOUT.CARE_CENTER_REDIRECT_BASE_URL.r=https://trn1-ccui.wsgc.com/oms/#/detail/order/default/
$UPDATE_SETTING SITE_SECURITY_CONFIGURATION.CONTENT_SECURITY_POLICY.s=frame-ancestors self *.wsgc.com carectruiprd.wsgc.com oms.wsgc.com carectruiprd-dr.wsgc.com oms-dr.wsgc.com trn1-wcc.wsgc.com trn1-sterling.wsgc.com trn1-ccui.wsgc.com eqa2-ccui.wsgc.com eqa2-sterling.wsgc.com eqa2-wcc.wsgc.com
$UPDATE_SETTING SINGLE_PAGE_CHECKOUT.CONTENT_SECURITY_POLICY.s=frame-ancestors self *.wsgc.com carectruiprd.wsgc.com oms.wsgc.com carectruiprd-dr.wsgc.com oms-dr.wsgc.com trn1-wcc.wsgc.com trn1-sterling.wsgc.com trn1-ccui.wsgc.com eqa2-ccui.wsgc.com eqa2-sterling.wsgc.com eqa2-wcc.wsgc.com
$UPDATE_SETTING CHKT.MINIMUM_CARE_CENTER_B2B_CONSOLIDATION_THRESHOLD.n=10000
$UPDATE_SETTING CARE_CENTER_CONFIGURATION.JWT_ALLOWED_CLOCK_SKEW.t=0,0,3,0
$UPDATE_SETTING SINGLE_PAGE_CHECKOUT.CARE_CENTER_FINAL_ORDER_ENABLED.b=true

{ set +x; } 2>/dev/null

echo "* update $(basename $POM)"
#set -x
propset -f $POM -p frontend.jmsOrder.providerUrl -v tcp://tibinttstmp3p.wsgc.com:20011
propset -f $POM -p frontend.jmsOrder.username -v apptibco  
propset -f $POM -p frontend.jmsOrder.password -v n3tw0rk 
propset -f $POM -p frontend.jmsOrderPricing.providerUrl -v tcp://tibinttstmp3p.wsgc.com:20011
propset -f $POM -p frontend.jmsOrderPricing.username -v apptibco 
propset -f $POM -p frontend.jmsOrderPricing.password -v n3tw0rk 
propset -f $POM -p frontend.jmsOrderCreate.providerUrl -v tcp://tibinttstmp3p.wsgc.com:20011
propset -f $POM -p frontend.jmsOrderCreate.username -v apptibco 
propset -f $POM -p frontend.jmsOrderCreate.password -v n3tw0rk 
propset -f $POM -p frontend.jmsOrderReservation.providerUrl -v tcp://tibinttstmp3p.wsgc.com:20011
propset -f $POM -p frontend.jmsOrderReservation.username -v apptibco 
propset -f $POM -p frontend.jmsOrderReservation.password -v n3tw0rk 
propset -f $POM -p frontend.jms.providerUrl -v tcp://tibinttstmp3p.wsgc.com:20011
propset -f $POM -p frontend.jms.username -v apptibco
propset -f $POM -p frontend.jms.password -v n3tw0rk
propset -f $POM -p frontend.jms.subscriberClientId -v @NODENAME@
propset -f $POM -p frontend.jmsWismo.username -v apptibco
propset -f $POM -p frontend.jmsWismo.password -v n3tw0rk
propset -f $POM -p frontend.jmsWismo.usernameCov2 -v apptibco
propset -f $POM -p frontend.jmsWismo.passwordCov2 -v n3tw0rk
{ set +x; } 2>/dev/null

if [[ $MARKET = "CAN" ]]
then
  echo "* update $MARKET-specific settings"


{ set +x; } 2>/dev/null
fi

