#!/bin/bash
PATH=/apps/mead-tools:/apps:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/opt/homebrew/bin:~/bin

site=$1

[ -z "$site" ] && exit 1

case $site in
	66 ) echo  ;;
	76 ) echo "can" ;;

	63 ) echo  ;;
	73 ) echo "can" ;;

	65 ) echo  ;;
	75 ) echo "can" ;;

	67 ) echo  ;;
	77 ) echo "can" ;;

	69 ) echo  ;;
	79 ) echo "can" ;;

	61 ) echo  ;;
	71 ) echo "can" ;;

	* ) exit 1 ;;
esac

exit 0
