#!/bin/bash
# translates cat generation number to the actual directory name
BUILD=
GEN=$(echo "$1" | awk -F \. '{ print $1 }')

#GEN=270236115
[[ -z $GEN ]] && exit 1
[[ ${#GEN} != 9 ]] && exit 1

G="${GEN:0:1}"

if [[ $G = 8 ]]
then
  S="${GEN:(-4)}"
  B="${GEN:0:${#GEN}-4}"
  B="${B:1}"
  BUILD="20${B}-${S}"
fi

if [[ $G = "4" || $G = "3" ]]
then
  S="${GEN:(-2)}"
  B="${GEN:0:${#GEN}-2}"
  B="${B:1}"
  BUILD="20${B}-${G}${S}"
fi

echo "$BUILD"
